### ISSUE TITLE
Does not build today

### ISSUE THREAD

**Issue by quicklisp** [guicho271828/trivialib.type-unify#1]
http://report.quicklisp.org/2015-12-07/failure-report/trivialib.type-unify.html#trivialib.type-unify has a log.

Mostly macroexpansion errors?

**Comment by guicho271828** [comment]
thanks for the report, I'm looking into this.

**Comment by guicho271828** [comment]
this is due to the wrong behavior of newly added feature in trivia (inline pattern).

**Comment by guicho271828** [comment]
Fixed trivia in https://github.com/guicho271828/trivia/issues/21 .
As a result I can compile type-unify on my computer.
