### ISSUE TITLE
Test system does not build

### ISSUE THREAD

**Issue by quicklisp** [guicho271828/trivialib.type-unify#3]
Log is here: http://report.quicklisp.org/2016-08-15/failure-report/trivialib.type-unify.html#trivialib.type-unify.test

I get this: Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10033276F3}>: The valueTis not of typeSEQUENCE (sic)

I don't understand why, sorry.

**Comment by guicho271828** [comment]
this is due to the API change in fiveam and how to launch the test. will be fixed soon

**Comment by guicho271828** [comment]
I believe this is fixed in 62492ebf04db567dcf435ae84c50b7b8202ecf99 . (ignore ECL, cmuel and allegro, they have been broken for a while)
