### ISSUE TITLE
The test use set-equal without passing :test when needed. 

### ISSUE THREAD

**Issue by Yehouda** [guicho271828/trivialib.type-unify#5]
In the tests, alexandria:set-equal is used to compare the results. When the results contain objects that are not equal  with EQL, that fails. In particular, strings are not equal under eql unless they are exactly the same object. 

The two checks that set-eqal with (1 "aa") and with (5 "c") currently "fail" a a result. 

Adding :test 'equal to the arguments of set-equal fixes it.

**Comment by guicho271828** [comment]
thanks. it is a shame, the CI is not doing the job. It runs the test, which fails, but still reports "success".
https://travis-ci.org/guicho271828/trivialib.type-unify/jobs/152628871
